# Generated by Django 5.1.4 on 2025-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agenda_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
    ]
