# Generated by Django 5.1.4 on 2025-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_mode',
            field=models.CharField(choices=[('freechat', 'Free Chat'), ('questionanswer', 'Question and Answer')], default='freechat', max_length=50),
        ),
    ]
