# Generated by Django 5.1.4 on 2025-02-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation_handler", "0002_conversation_agenda_items_and_more"),
        ("conversation_handler", "0002_conversation_conversation_mode"),
    ]

    operations = []
