# Generated by Django 5.0.13 on 2025-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0002_conversation_agenda_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='session_number',
            field=models.IntegerField(default=0),
        ),
    ]
