# Generated by Django 5.1.4 on 2025-02-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation_handler", "0003_merge_20250217_0404"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="conversation_mode",
        ),
    ]
