# Generated by Django 5.1.4 on 2025-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0004_remove_conversation_conversation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='session_number',
            field=models.IntegerField(default=0),
        ),
    ]
