# Generated by Django 5.1.5 on 2025-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0005_alter_conversation_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_sub_items',
            field=models.JSONField(default=dict),
        ),
    ]
