# Generated by Django 5.1.4 on 2025-04-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_handler', '0006_conversation_current_sub_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='isCrisisModeActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_sub_items',
            field=models.JSONField(default=list),
        ),
    ]
